#.github\workflows\schedule.yml
on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: ${{ secrets.GITH_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
        SKIP_UPDATED: '1'